#!/bin/sh
set -e

REPO="hcl-team-dev-org/hcl-commerce-skill"
BRANCH="main"
BASE_URL="https://raw.githubusercontent.com/$REPO/$BRANCH/.claude/commands"

SKILLS="hcl-setup hcl-plp hcl-pdp hcl-cart hcl-checkout hcl-search hcl-inventory hcl-categories"

mkdir -p .claude/commands

installed=0
skipped=0

for skill in $SKILLS; do
  url="$BASE_URL/$skill.md"
  target=".claude/commands/$skill.md"
  http_status=$(curl -s -o "$target" -w "%{http_code}" "$url")
  if [ "$http_status" = "200" ]; then
    echo "  installed /$skill"
    installed=$((installed + 1))
  else
    rm -f "$target"
    skipped=$((skipped + 1))
  fi
done

cat > CLAUDE.md << 'EOF'
# HCL Commerce Storefront

This is a demo storefront built with [hcl-commerce-skill](https://github.com/hcl-team-dev-org/hcl-commerce-skill) for HCL Commerce sales engineering.

## Purpose

This project exists to demonstrate HCL Commerce to a prospect — a working, industry-specific storefront built live against a real backend in a single session. The goal is a credible, vertical-specific demo, not a production codebase.

## How it works

Three components work together:

- **MCP server** (configured in `.mcp.json`) — a live proxy to the HCL Commerce backend. Claude calls it during a session to verify real API responses before writing code.
- **Skills** (in `.claude/commands/`) — slash commands that give Claude deep HCL Commerce knowledge: API patterns, data shapes, Next.js conventions, and common pitfalls.
- **This project** — the Next.js App Router storefront generated by those skills against the connected backend.

## Storefront brief

If `STOREFRONT.md` exists in this directory, read it before making any UI or design decisions. It defines the brand, tone, visual direction, and emphasis for this specific demo. Always respect it.

If it does not exist and you are about to build UI, stop and ask the user to describe what they are building before proceeding.

## Skill debugging

The skills in `.claude/commands/` are the source of truth for how this storefront is built. If generated code has a structural problem — wrong API call, missing pattern, wrong assumption — the fix belongs in the skill file, not in the generated code.

When you identify a skill issue:
1. Edit the relevant `.claude/commands/*.md` file to fix the root cause
2. Tell the user to rerun the command
3. Do not patch generated output as a workaround

## Key conventions

- `lib/commerce/client.ts` — base fetch wrapper for HCL Commerce APIs
- `lib/commerce/images.ts` — always use `getImageUrl()` for image paths
- `lib/commerce/session.ts` — guest session management
- Tokens (`WCToken`, `WCTrustedToken`) are server-side only, stored in httpOnly cookies
- `cache: 'no-store'` on all commerce fetches — demo needs live data
EOF

echo ""
echo "HCL Commerce skills installed: $installed (skipped unavailable: $skipped)"
echo "Created CLAUDE.md with project context."
echo "Run /hcl-setup in Claude Code to get started."
